server:
    port: 8082
spring:
    jpa:
        generate-ddl: true
        open-in-view: false
    hibernate:
        ddl-auto: create-drop
    profiles:
        active: h2
springdoc:
    swagger-ui.path: /catalog-service/swagger-ui.html
