server:
    port: 8080
spring:
    jpa:
        generate-ddl: true
        open-in-view: false
    hibernate:
        ddl-auto: create-drop
    docker:
        compose:
            file: ./docker-compose.yaml
springdoc:
    swagger-ui.path: /payment-service/swagger-ui.html
