server:
    port: 8080
spring:
    datasource:
        hikari:
            connection-timeout: 250
    jpa:
        generate-ddl: true
        open-in-view: false
    hibernate:
        ddl-auto: create-drop
    docker:
        compose:
            file: ./docker-compose.yaml
    kafka:
        consumer:
            group-id: payment-service
            properties:
                spring.json.trusted.packages: org.oka.aka.paymentservice.model
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        bootstrap-servers: localhost:9092
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

springdoc:
    swagger-ui.path: /payment-service/swagger-ui.html