server:
    port: 80
spring:
    application:
        name: gateway-service
    cloud:
        gateway:
            routes:
                - id: catalogservice
                  uri: http://localhost:8082
                  predicates:
                    - Path=/catalogservice/**
                  filters:
                    - PrefixPath=/api
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS